//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHangNhap
    {
        public string MaDN { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string MaChiNhanh { get; set; }
        public Nullable<int> LoaiSP { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual DonNhapHang DonNhapHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
