//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public string MaDH { get; set; }
        public string MaSanPham { get; set; }
        public Nullable<int> SoLuongSanPham { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string MaChiNhanh { get; set; }
        public Nullable<double> GiaSP { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
