//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public string MaDH { get; set; }
        public Nullable<System.DateTime> NgayDH { get; set; }
        public string PTTT { get; set; }
        public string TenNguoiNhan { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChiChiTiet { get; set; }
        public string Tinh { get; set; }
        public string Huyen { get; set; }
        public string Phuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string MaCTKM { get; set; }
        public Nullable<double> GiaGiam { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
    }
}
