//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string MaKhachHang { get; set; }
        public string HoKH { get; set; }
        public string TenKH { get; set; }
        public string GioiTinh { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string NgaySinh { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> LoaiTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
